-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT, N.FISH_NAME AS FISH_NAME
FROM FISH_NAME_INFO N
    INNER JOIN FISH_INFO I
    ON N.FISH_TYPE = I.FISH_TYPE
GROUP BY N.FISH_TYPE, N.FISH_NAME
ORDER BY `FISH_COUNT` DESC;