-- 코드를 입력하세요
SELECT ai.NAME, ai.DATETIME -- 이름, 보호 시작일
FROM ANIMAL_INS AS ai
    LEFT JOIN ANIMAL_OUTS AS ao
        ON ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE ao.DATETIME IS NULL
ORDER BY ai.DATETIME
LIMIT 3;