-- 식품 ID, 식품 이름, 총매출
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A -- 식품 정보 테이블
    INNER JOIN FOOD_ORDER B -- 식품 주문 정보 테이블
    ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;