-- 회원 ID, 닉네임, 개인 총거래금액 조회
SELECT B.WRITER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B -- 중고 거래 게시판 정보 테이블
    INNER JOIN USED_GOODS_USER U -- 중고 거래 게시판 사용자 정보 테이블
    ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES; 